### ISSUE TITLE
Expand setup instructions and in particular how to download julia

### ISSUE THREAD

**Issue by amanmdesai** [carpentries-incubator/julia-novice#36]

**Comment by BeastyBlacksmith** [comment]
Which operating system are you on? The windows version is quite detailed. The others could have more specific instructions.

**Comment by amanmdesai** [comment]
Linux -- julia download

Current instruction:
"Download the current stable release from the [Julia download page](https://julialang.org/downloads/) and unpack the folder to any location that is in your PATH or link the binary in the bin folder to such a location."

I believe that it should be better to add explicit instructions/commands in the module itself.

**Comment by kescobo** [comment]
I think it could be time to recommend `juliaup` as the primary way to do this.

**Comment by BeastyBlacksmith** [comment]
@all-contributors add @amanmdesai for userTesting
