### ISSUE TITLE
Comparisons with Python/R

### ISSUE THREAD

**Issue by qualiaMachine** [carpentries-incubator/julia-novice#40]
In the Introduction episode, I think it would be really beneficial to list some of the pros/cons of choosing Julia vs some of the (currently) more popular languages such as Python and R. I'm wondering about some of those pros and cons, myself. Could we maybe use this issue/thread to compile a list of some of the reasons to pick one of the languages versus another?

**Comment by kescobo** [comment]
I like this explanation: https://juliadatascience.io/why_julia from @storopoli

**Comment by storopoli** [comment]
Thanks @kescobo.

There's also https://storopoli.github.io/Bayesian-Julia/pages/01_why_Julia/ which is a little more technical if you want to go under the hood.

**Comment by BeastyBlacksmith** [comment]
> I think it would be really beneficial to list some of the pros/cons of choosing Julia vs some of the (currently) more popular languages such as Python and R

Honestly, I want people to evaluate that for themself. Why it's useful to me might be irrelevant for someone else and it's easy to end up in an argument over this or that claim.
I tried to make this an unbiased to the things the language does well as I could. Though highlighting why certain aspects are outstandingly good (like the seemless interaction of self defined type, ForwardDiff and a generic written algorithm) is not as easy as I thought.

**Comment by giordano** [comment]
I'm with @BeastyBlacksmith here: I'm not sure it should be the purpose of a lesson to "advocate" for a tool, I think it should teach skills, students can evaluate them and decide whether they like them or not, or how to generalise them.
