### ISSUE TITLE
Add conclusion?

### ISSUE THREAD

**Issue by gus-pendleton** [carpentries-incubator/julia-novice#54]
Would it be helpful to add a conclusion, summarizing the key points of the lesson and pointing out Julia community resources (Discourse, Slack, etc.) and domain-specific Julia projects (e.g. BioJulia)? I'm imagining this more for users who are working through this lesson alone online, as opposed to in-class with instructors. I'd be happy to take this on if people think it's worthwhile.

**Comment by kescobo** [comment]
That sounds like a great idea to me!

**Comment by gus-pendleton** [comment]
Okay, done! I want to make sure I do this correctly - should I only edit the Literate .jl files and commit those changes, or should I run the generate script and commit all of the output as well?

**Comment by BeastyBlacksmith** [comment]
The generate script will be automatically run when the PR gets merged. But you light want to look at the generated files beforehand

**Comment by BeastyBlacksmith** [comment]
done in https://github.com/carpentries-incubator/julia-novice/pull/58
