### ISSUE TITLE
Duplicate sections in the course

### ISSUE THREAD

**Issue by giordano** [carpentries-incubator/julia-novice#68]
The course at https://carpentries-incubator.github.io/julia-novice/index.html shows several duplicate sections: 
![image](https://github.com/carpentries-incubator/julia-novice/assets/765740/586ee455-a444-4700-a0b1-f7111ce28b6d)

**Comment by BeastyBlacksmith** [comment]
Fixed by b5b88a9 though would be nice, if we could catch file renames automatically

**Comment by BeastyBlacksmith** [comment]
@all-contributors add @giordano for userTesting
